"""Is the artefact executing this run the one the run was launched for?

CI VALIDATES THE REPOSITORY. IT NEVER VALIDATES WHAT IS DEPLOYED. Every test in
this project reads the working tree, so a green Databricks run is evidence about
the artefact sitting in the workspace -- and that artefact is `HEAD` only if
somebody deployed `HEAD`, a separate act performed by hand with no check behind
it. F1.4b PR A lost that bet twice in one day: a wheel older than every commit on
the branch reached a run, and a socios re-run reported SUCCESS having masked only
bronze because the workspace was still running a bundle deployed four commits
earlier. Nothing went red either time. Both were found by a human reading a task
log against the source.

TWO VALUES FROM TWO PLACES, which is the whole of it (ADR 0009):

* the EXPECTED revision arrives from the launch -- `--params
  revision=$(git rev-parse HEAD)` -- so it is the operator's local `HEAD` at the
  moment the run was submitted;
* the ACTUAL revision is read out of the deployed wheel, which carries an
  `opl/_revision.py` generated by `hatch_build.py` at build time.

Read both from the same place and the check passes always while looking exactly
like a working one. That is why nothing in this module goes and finds either value
for itself: it consults no repository, starts no session, reads no file. A
deploy-time expected value has the same defect in a subtler form -- it catches a
stale wheel inside a fresh deploy and passes the deploy that never happened, which
is the incident above.

THIS MODULE IS NOT BRONZE-SPECIFIC. It lives here because every job that carries
the guard today is a bronze job; when a silver or gold layer arrives it belongs
beside `opl._version_check`, which is the same category of question asked about the
same artefact."""
from __future__ import annotations

import importlib
import re
from typing import NoReturn

# The `revision` job-parameter default in every guarded job YAML, and a value this
# module refuses. A job parameter must have SOME default and no revision is a valid
# one, so the default's whole job is to fail -- same shape and same reason as
# `opl.bronze.promote.SENTINEL_BATCH_ID`. `tests/test_job_yaml_wiring.py` asserts
# that each YAML default is a value `is_object_name` rejects, because a default that
# happened to be a real object name would make every run launched without
# `--params revision=...` pass against a commit nobody chose.
SENTINEL_REVISION = "REQUIRED-PASS-A-REVISION"

# Where the deployed artefact states its own provenance. Generated INTO THE WHEEL by
# the build hook and deliberately absent from the source tree, so that an editable
# install -- which points at a tree that changes under it -- carries no revision at
# all and cannot satisfy this check.
#
# PUBLIC because it is a CONTRACT WITH THE BUILD, not an internal detail: the hook
# force-includes a file at a path, and this is the import that path has to satisfy.
# A mutation probe made the case for exposing it -- pointing the hook's destination at
# the wheel root instead of inside the package left every test green while
# `opl._revision` became unimportable, i.e. while every guarded job refused every run,
# because each test named the same constant the hook did.
STAMP_MODULE = "opl._revision"
_STAMP_ATTRIBUTE = "REVISION"

# A WHOLE object name and nothing else. One rule refuses the sentinel, an empty
# string, a branch name, `HEAD`, and an abbreviated SHA -- the abbreviation because
# these two values are compared for equality, and accepting a prefix would mean
# deciding how short a prefix is still evidence. 64 digits is here for a repository
# that ever moves to SHA-256 object names; this one is SHA-1 today.
_OBJECT_NAME = re.compile(r"^(?:[0-9a-f]{40}|[0-9a-f]{64})$")

_LAUNCH_HINT = "--params revision=$(git rev-parse HEAD)"
_DEPLOY_HINT = "databricks bundle deploy -t free"


class WrongRevision(RuntimeError):
    """This run cannot show that it is executing the code it was launched for.

    ONE EXCEPTION FOR ALL FOUR REFUSALS -- no expected value, no stamp, a different
    commit, a modified tree -- because operationally they say the same thing, and a
    caller that wanted to tell them apart would be a caller deciding to continue on
    one of them. Continuing is the failure this guard exists to prevent. The messages
    differ; the verdict does not."""


def _normalised(value: str | None) -> str:
    """Absent, padded and upper-case all collapse to one comparable form.

    `git rev-parse HEAD` prints lower case, so the tolerance is for a hand-pasted
    value and for a shell that hands the parameter through with a trailing newline.
    Neither of those is a stale deployment, and a refusal that cannot be told apart
    from one wastes the operator's time in the direction that teaches them to
    distrust the guard."""
    return (value or "").strip().lower()


def is_object_name(value: str | None) -> bool:
    """Is `value` a whole git object name? THE one spelling of that rule.

    Public because the job-YAML lock asks it about each `revision:` default rather
    than restating the shape. Two spellings of one rule is how `2026-13` came to be
    refused at two of four entry points (see `opl.config.is_month`)."""
    return _OBJECT_NAME.match(_normalised(value)) is not None


def built_revision() -> str:
    """The revision the RUNNING artefact was built from, or `""` if it does not say.

    An empty answer is not "unknown, carry on" -- `assert_revision_matches` refuses
    it. Three things produce it: a local editable install (by design), a wheel built
    where git could not answer, and a wheel built by some path that does not stamp.
    All three mean the same thing, which is that nothing here can name the source of
    the code about to run.

    The `ModuleNotFoundError` is narrowed to the stamp itself. A stamp that existed
    but failed to import for its own reasons must raise rather than read as absent:
    that is a corrupt artefact, and reporting it as "unstamped" would send the
    operator to deploy again over a wheel whose problem a deploy does not fix."""
    try:
        stamp = importlib.import_module(STAMP_MODULE)
    except ModuleNotFoundError as absent:
        if absent.name != STAMP_MODULE:
            raise
        return ""
    return _normalised(getattr(stamp, _STAMP_ATTRIBUTE, ""))


def assert_revision_matches(*, expected: str | None, actual: str | None) -> str:
    """The verified revision, or refuse. `expected` from the launch, `actual` from the
    deployed artefact -- never the other way round and never the same source twice.

    KEYWORD-ONLY, deliberately: the two arguments have the same type and the same
    shape, so a positional call site that swapped them would still compare the right
    two values and then describe the failure backwards -- telling an operator to
    deploy when the wheel is fine and their parameter is stale."""
    launched_for = _normalised(expected)
    if not is_object_name(launched_for):
        _refuse_the_expected_revision(expected)
    deployed = _normalised(actual)
    if not deployed:
        _refuse_an_unstamped_artefact(launched_for)
    if deployed == launched_for:
        return launched_for
    _refuse_the_mismatch(launched_for, deployed)


def _refuse_the_expected_revision(expected: str | None) -> NoReturn:
    raise WrongRevision(
        f"refusing to run: revision={expected!r} is not a revision this run can be "
        "checked against. It must be a whole git object name -- 40 hex digits, exactly "
        f"what `git rev-parse HEAD` prints. Launch the run with `{_LAUNCH_HINT}`.\n"
        f"If that value is {SENTINEL_REVISION!r}, the job parameter was left at its "
        "default and no --params reached this run: the default is a value this check "
        "refuses on purpose, because a job parameter must have one and no revision is "
        "valid.\n"
        "An absent expected value is REFUSED rather than skipped. 'Nothing to compare' "
        "would switch the check off in exactly the case it exists for -- a run launched "
        "by a path that forgot the parameter -- and a guard that is absent when it is "
        "needed is worse than none, because the next reader believes the hole is closed."
    )


def _refuse_an_unstamped_artefact(expected: str) -> NoReturn:
    raise WrongRevision(
        "refusing to run: the deployed artefact does not say what revision it was built "
        f"from, so nothing here can show that this run executes {expected}. The revision "
        "is generated into the wheel by hatch_build.py when `uv build --wheel` runs, "
        f"which is what `{_DEPLOY_HINT}` runs. An unstamped wheel therefore means the "
        "installed artefact did not come from that path -- a local editable install "
        "carries no stamp by design (ADR 0009), and a wheel built outside a checkout "
        "cannot know -- or that pip installed something other than the wheel this bundle "
        f"builds. Run `{_DEPLOY_HINT}` and launch again."
    )


def _refuse_the_mismatch(expected: str, actual: str) -> NoReturn:
    """Three ways the two values differ, and they need three different instructions.

    Split by what `actual` IS rather than by how far apart the two are: a modified
    tree is fixed by a commit, a different commit by a deploy, and a stamp that is not
    an object name at all by finding out what wrote it. Collapsing them into one
    message would send an operator to re-deploy the same dirty tree and watch the same
    refusal, which is how a guard gets routed around."""
    if is_object_name(actual):
        raise WrongRevision(
            f"refusing to run: the deployed wheel was built from {actual}, and this run "
            f"was launched for {expected}. Different commits -- so every task after this "
            "one would execute code that is not the code you are reading.\n"
            f"The likeliest cause is the simplest: nobody ran `{_DEPLOY_HINT}` since "
            f"{expected}. CI validates the repository and never what is deployed, so "
            "nothing else would have gone red. It can also be a stale wheel inside a "
            "fresh deploy -- the jobs receive the wheel through the glob "
            '`dependencies: ["../../dist/*.whl"]` over a dist/ that nothing cleans.\n'
            "Deploy, then launch again with the same revision."
        )
    if actual.startswith(expected):
        raise WrongRevision(
            f"refusing to run: the deployed wheel names this run's commit {expected} but "
            f"was built from a MODIFIED tree -- its stamp is {actual!r}. `git rev-parse "
            "HEAD` answers identically in a dirty tree, so without this the wheel would "
            "claim a commit that does not describe its own contents, and the provenance "
            "line in the log would be false in the one direction nobody thinks to check. "
            "Something under src/ or pyproject.toml held uncommitted changes when the "
            "wheel was built.\n"
            "The fix is `git commit` (or `git stash`), then deploy and launch again -- "
            "re-deploying the same tree reproduces this refusal."
        )
    raise WrongRevision(
        f"refusing to run: the deployed artefact reports {actual!r} as the revision it "
        f"was built from, which is not a git object name, and this run was launched for "
        f"{expected}. Nothing in the documented build writes that value, so the question "
        "is what did: find out before running anything against this deployment."
    )
