# tests/test_bundle_targets_and_schedules.py
"""Which jobs declare a cadence, and WHO writes `pause_status`.

WHICH HALF IS ASSERTED HERE AND WHICH IS NOT -- read this before trusting the green.

  * ASSERTED, CREDENTIAL-FREE, IN CI: everything about the COMMITTED SOURCE. Every YAML
    under `databricks/resources/` is classified scheduled or not, with a reason; a
    scheduled job declares a cron and a timezone and nothing else that fires it; an
    unscheduled one declares no `schedule`, `trigger` or `continuous`; and **no committed
    bundle file DECLARES `pause_status` at any depth** (the values, not the text -- the
    schedule comments explain the key, and the explanation is not the defect). Both
    targets are read out of
    `databricks/databricks.yml`, and `prod`'s root path must be interpolated rather than
    carry an operator's identity.

  * NOT ASSERTED IN CI: the RENDERING. `pause_status` is written by the CLI from the
    target's `mode`, and asking what it wrote means running `databricks bundle validate`,
    which needs credentials -- measured, not assumed: with the config file pointed
    elsewhere and `DATABRICKS_HOST`/`DATABRICKS_TOKEN` unset, `bundle validate -t free`
    exits 1 with *"default auth: cannot configure default credentials"*, because this
    bundle's dev-mode name prefix resolves the current user and its dashboard resource
    resolves a warehouse by `lookup:`. So the rendering arm below SKIPS when the CLI or
    the credentials are absent, and says so. It is not decoration: it is the only place
    the `PAUSED`/`UNPAUSED` split is observed rather than described, and it was run by
    hand on the tree that shipped it.

WHY THE SPLIT MATTERS AT ALL. `mode: development` renders `pause_status: PAUSED` and
`mode: production` renders `UNPAUSED`, from source that says neither. Write `pause_status`
into a job YAML and the target stops deciding: a schedule would then be unpaused under
`free` too, in a workspace where every guarded job refuses an unparameterised run (ADR
0021). The absence in the source is the mechanism, which is why absence is what is
asserted."""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess

import pytest
import yaml
from job_yaml import RESOURCES, job_of

_BUNDLE = RESOURCES.parent / "databricks.yml"

# The three keys that make a job start without an operator. `schedule` is the one this
# phase declares; `trigger` (file arrival) and `continuous` are refused everywhere, in
# both lists, because a job with a cadence AND a trigger has two, and nothing in this
# repository has argued for either.
_FIRING_KEYS = ("schedule", "trigger", "continuous")

# THE KEY NO COMMITTED FILE MAY CARRY. Not a style rule: it is what makes the target's
# mode the thing that decides, and a job YAML that writes it takes that decision away.
_PAUSE = "pause_status"

# WHICH JOBS DECLARE A CADENCE, AND WHY THAT ONE. The question every entry answers is
# "does something outside this repository decide when this job's input exists?" -- and
# where the answer is a person or another machine, the answer is no schedule.
_SCHEDULED = {
    "bronze_job.yml": "the RFB CNPJ snapshot is monthly",
    "bronze_empresas_job.yml": "the RFB CNPJ snapshot is monthly",
    "bronze_estabelecimentos_job.yml": "the RFB CNPJ snapshot is monthly",
    "bronze_socios_job.yml": "the RFB CNPJ snapshot is monthly",
    "bronze_ptax_job.yml": "the Banco Central publishes PTAX once per business day",
    "vault_empresa_job.yml": "follows the monthly empresas bronze it reads",
    "vault_estabelecimento_job.yml": "follows the monthly estabelecimentos bronze it reads",
    "vault_partner_job.yml": "follows the monthly socios bronze it reads",
    "vault_reference_job.yml": "follows the monthly lookup bronze it reads",
    "gold_dim_company_job.yml": "follows the empresa vault load, which follows the snapshot",
    "gold_pit_estabelecimento_job.yml": "follows the estabelecimento vault load",
}

# AND THE JOBS THAT DELIBERATELY HAVE NONE. Each reason is this repository's own, taken
# from the file's header rather than invented here.
_UNSCHEDULED = {
    "bronze_payments_job.yml": (
        "its input is GENERATED by this wheel, per profile, and `profile` is a choice "
        "rather than a cadence -- its default is a sentinel the generator refuses"
    ),
    "bronze_merchant_job.yml": (
        "its input is produced by a host-side extractor on a laptop, and this job's own "
        "header states the consequence: launched before the snapshot has landed it drains "
        "an empty directory and reports SUCCESS, which for THIS table is what a total "
        "deletion looks like and would end-date every key in the vault"
    ),
    "vault_merchant_job.yml": "follows the merchant bronze, which has no cadence to follow",
    "gold_conformed_dimensions_job.yml": (
        "its members ARE constants in the wheel -- the payment methods and a derived date "
        "span -- so it changes when the wheel changes, and a clock cannot observe that"
    ),
    "gold_fact_payment_job.yml": "follows the payments bronze, which has no cadence",
    "dataops_views_job.yml": (
        "it issues CREATE OR REPLACE VIEW over definitions that live in the wheel; the "
        "event that changes them is a deploy, not a date"
    ),
    "repromote_batch_job.yml": (
        "an operator action taken AFTER a human has read a quarantine table. Its own "
        "header names isolation -- nothing automated reaches it -- as a safety property"
    ),
    "triage_job.yml": "incident-driven: what it triages is whatever incidents exist",
    "streaming_managed_broker_job.yml": (
        "a recorded run against a trial broker with a dated lifetime, not a standing "
        "service (ADR 0019 Decision 6)"
    ),
    "smoke_job.yml": (
        "the probe you run when the deployment itself is in doubt. A cadence would make "
        "the diagnostic answer a question nobody asked (ADR 0009)"
    ),
}

# The file that declares no job at all, and therefore nothing that could fire.
_NON_JOB = {"dataops_dashboard.yml"}


def _classification_faults(root=RESOURCES) -> list[str]:
    """Whether the three lists above are TOTAL over the YAMLs actually present."""
    declared = set(_SCHEDULED) | set(_UNSCHEDULED) | _NON_JOB
    present = {path.name for path in root.glob("*.yml")}
    if declared == present:
        return []
    return [
        f"unclassified: {sorted(present - declared)}; "
        f"classified but absent: {sorted(declared - present)}"
    ]


def _schedule_of(job: dict) -> dict:
    return job.get("schedule") or {}


def _firing_keys(job: dict) -> list[str]:
    return [key for key in _FIRING_KEYS if job.get(key)]


def _schedule_faults(root=RESOURCES) -> list[str]:
    """Every YAML present under `root`, against what its classification promises."""
    faults = []
    for path in sorted(root.glob("*.yml")):
        name = path.name
        if name in _NON_JOB:
            continue
        job = job_of(name, root)
        firing = _firing_keys(job)
        if name in _SCHEDULED:
            schedule = _schedule_of(job)
            if firing != ["schedule"]:
                faults.append(f"{name}: declares {firing or 'nothing that fires it'}")
            for key in ("quartz_cron_expression", "timezone_id"):
                if not schedule.get(key):
                    faults.append(f"{name}: its schedule declares no {key}")
            if _PAUSE in schedule:
                faults.append(f"{name}: writes {_PAUSE}, taking the decision off the target")
        elif name in _UNSCHEDULED and firing:
            faults.append(f"{name}: is declared unscheduled and yet declares {firing}")
    return faults


def _keys_anywhere(node) -> set[str]:
    """Every mapping key at any depth of a parsed document."""
    if isinstance(node, dict):
        return set(node) | {k for v in node.values() for k in _keys_anywhere(v)}
    if isinstance(node, list):
        return {k for item in node for k in _keys_anywhere(item)}
    return set()


def _pause_status_faults(docs: dict[str, object]) -> list[str]:
    """No committed bundle file may DECLARE the key, at any depth.

    OVER THE PARSED DOCUMENT AND NOT THE RAW TEXT, which is the shape
    `tests/dataops/test_dashboard.py` already settled for the committed warehouse id:
    prose naming the hazard is not the hazard. Every schedule block in this bundle
    carries a comment saying that `pause_status` is the target's to write and not the
    source's -- a text sweep would refuse the explanation along with the defect, and a
    rule that cannot state its own reason is one the next author deletes. Comments are
    gone by the time YAML is a document, so what is checked is what would deploy."""
    return [
        f"{name}: declares {_PAUSE}"
        for name, doc in docs.items()
        if _PAUSE in _keys_anywhere(doc)
    ]


def _bundle_docs() -> dict[str, object]:
    root = RESOURCES.parent
    return {
        str(path.relative_to(root)): yaml.safe_load(path.read_text(encoding="utf-8"))
        for path in sorted(root.rglob("*.yml"))
    }


def _target_faults(bundle_text: str) -> list[str]:
    """The two targets, and what each is for. Read out of the committed bundle root."""
    targets = yaml.safe_load(bundle_text)["targets"]
    faults = []
    if targets.get("free", {}).get("mode") != "development":
        faults.append(f"target `free` is {targets.get('free')}, not mode: development")
    if not targets.get("free", {}).get("default"):
        faults.append("target `free` is no longer `default: true`")
    prod = targets.get("prod", {})
    if prod.get("mode") != "production":
        faults.append(f"target `prod` is {prod}, not mode: production")
    root_path = prod.get("workspace", {}).get("root_path", "")
    if "${workspace.current_user.userName}" not in root_path:
        # `mode: production` refuses to validate without a root_path; the CLI's own
        # suggestion is a LITERAL user name, and taking it would commit an identity.
        faults.append(f"target `prod` root_path {root_path!r} is not interpolated")
    if "@" in root_path:
        faults.append(f"target `prod` root_path {root_path!r} carries a literal identity")
    return faults


def test_every_job_yaml_is_classified_scheduled_or_not():
    """TOTAL over `databricks/resources/*.yml`, so a new job cannot inherit an answer.

    The question -- does something outside this repository decide when this job's input
    exists? -- has an answer for every job, and half of them answer no. Left to a glob,
    a job added later would silently join the unscheduled majority without anyone saying
    why, which is how the guard classification in `test_job_yaml_launch_guards.py` came to
    be exact in both directions too."""
    assert not _classification_faults()


def test_the_scheduled_jobs_declare_a_cron_a_zone_and_nothing_else_that_fires_them():
    """A cadence is a cron plus a zone. `trigger` and `continuous` are refused in both
    lists: a job with two ways of starting has two cadences and this bundle argues one."""
    assert not _schedule_faults()


def test_no_committed_bundle_file_writes_pause_status():
    """THE MECHANISM, ASSERTED AS AN ABSENCE.

    `pause_status` is written by the CLI from the target's `mode` -- `PAUSED` under
    `development`, `UNPAUSED` under `production`. A job YAML that writes it takes that
    decision away from the target, and the failure is silent: the schedule simply is not
    paused where the deployment mode says it should be. Swept over every committed bundle
    file -- the bundle root and every resource -- at any depth of the parsed document.
    `_pause_status_faults` carries why the sweep is over values rather than text."""
    assert not _pause_status_faults(_bundle_docs())


def test_the_bundle_declares_the_two_targets_this_split_needs():
    """`free` stays the default development target; `prod` exists to be the other mode."""
    assert not _target_faults(_BUNDLE.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------------
# THE RENDERING. The only place the split is OBSERVED, and it needs credentials.
# --------------------------------------------------------------------------------


def _rendered(target: str) -> dict:
    """`databricks bundle validate -t <target> -o json`, or skip with the reason."""
    cli = shutil.which("databricks")
    if cli is None:
        pytest.skip("no `databricks` CLI on PATH; the rendering half cannot run here")
    done = subprocess.run(
        [cli, "bundle", "validate", "-t", target, "-o", "json"],
        cwd=RESOURCES.parent, capture_output=True, text=True,
        env={**os.environ, "MSYS_NO_PATHCONV": "1"},
    )
    if done.returncode:
        pytest.skip(f"`bundle validate -t {target}` failed: {done.stderr.strip()[:200]}")
    return json.loads(done.stdout)["resources"]["jobs"]


def _rendered_pause_statuses(target: str) -> dict[str, str | None]:
    """What the CLI wrote as `pause_status` for each job that declares a schedule."""
    return {
        key: (job.get("schedule") or {}).get(_PAUSE)
        for key, job in _rendered(target).items()
        if job.get("schedule")
    }


@pytest.mark.parametrize(("target", "expected"), [("free", "PAUSED"), ("prod", "UNPAUSED")])
def test_the_target_mode_is_what_writes_pause_status(target: str, expected: str):
    """BOTH targets rendered, and the same source yielding the opposite value.

    SKIPS WITHOUT CREDENTIALS -- see this module's docstring for the measurement that
    says why that cannot be helped. A skip is not a pass and the reason is printed."""
    rendered = _rendered_pause_statuses(target)
    assert len(rendered) == len(_SCHEDULED), (
        f"-t {target} rendered {len(rendered)} scheduled jobs; the source declares "
        f"{len(_SCHEDULED)}"
    )
    wrong = {key: value for key, value in rendered.items() if value != expected}
    assert not wrong, f"-t {target} ({expected} expected) rendered {wrong}"


# --------------------------------------------------------------------------------
# THE FAILURE ARMS. Each mutation is DERIVED from the file, never typed beside it.
# --------------------------------------------------------------------------------

_SCHEDULE_BLOCK = re.compile(
    r"^ +schedule:\n(?: +\w+: .*\n)+", re.M
)


def _a_scheduled_job() -> tuple[str, str]:
    """The first classified-scheduled YAML and its text. NOT a filename typed here: a
    renamed job would then be punished by the arm instead of by the classification."""
    name = sorted(_SCHEDULED)[0]
    return name, (RESOURCES / name).read_text(encoding="utf-8")


def _copy_one(tmp_path, name: str, text: str):
    root = tmp_path / "resources"
    root.mkdir(parents=True, exist_ok=True)
    (root / name).write_text(text, encoding="utf-8")
    return root


def test_the_lock_goes_red_when_a_scheduled_job_loses_its_schedule(tmp_path):
    """Delete the block -- found by shape, so the cron is never typed into this arm.

    THE PRISTINE COPY IS CHECKED FIRST, and that is not ceremony. Without it the arm
    passes whenever a copied YAML produces a fault for ANY reason -- a broken copy, a
    reader that cannot find the job -- and would go on passing after the lock it exercises
    had stopped working."""
    name, text = _a_scheduled_job()
    assert not _schedule_faults(_copy_one(tmp_path / "pristine", name, text))
    found = _SCHEDULE_BLOCK.search(text)
    assert found, f"{name} carries no schedule block for this arm to remove"
    root = _copy_one(tmp_path / "cut", name, text.replace(found.group(0), "", 1))
    faults = _schedule_faults(root)
    assert any(name in fault and "nothing that fires it" in fault for fault in faults), faults


def test_the_sweep_goes_red_when_a_pause_status_is_written_into_the_source(tmp_path):
    """Paste the CLI's own key back into a job YAML and both halves must notice."""
    name, text = _a_scheduled_job()
    assert not _pause_status_faults({name: yaml.safe_load(text)})
    assert not _schedule_faults(_copy_one(tmp_path / "pristine", name, text))
    found = _SCHEDULE_BLOCK.search(text)
    assert found, f"{name} carries no schedule block for this arm to extend"
    mutated = text.replace(found.group(0), f'{found.group(0)}        {_PAUSE}: UNPAUSED\n', 1)
    assert mutated != text
    assert _pause_status_faults({name: yaml.safe_load(mutated)})
    root = _copy_one(tmp_path / "pasted", name, mutated)
    assert any(_PAUSE in fault for fault in _schedule_faults(root))


def test_the_target_lock_goes_red_when_prod_commits_an_identity():
    """Swap the interpolation for a literal -- a FABRICATED one, never this box's."""
    text = _BUNDLE.read_text(encoding="utf-8")
    token = "${workspace.current_user.userName}"
    assert token in text, "the bundle no longer interpolates the user; re-point this arm"
    faults = _target_faults(text.replace(token, "someone@example.invalid"))
    assert any("literal identity" in fault for fault in faults), faults
    assert any("not interpolated" in fault for fault in faults), faults
